import { useEffect } from "react";
import Promise from "promise";

// Grants a one-time welcome bonus a few seconds after the UI mounts, using the
// Promise package's scheduler. Demonstrates importing a typed wally package:
// `Promise` resolves with real types generated by `rbx-tsx types`.
export function useWelcomeBonus(
  delaySeconds: number,
  amount: number,
  onGrant: (amount: number) => void
) {
  useEffect(() => {
    const pending = Promise.delay(delaySeconds).andThen(() => {
      onGrant(amount);
    });

    return () => {
      pending.cancel();
    };
  }, [delaySeconds, amount, onGrant]);
}
