import { describe, test, expect, beforeAll, afterAll } from "bun:test";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";

const cliPath = join(import.meta.dir, "..", "..", "src", "index.ts");

function runCompile(args: string[]) {
	const result = Bun.spawnSync([process.execPath, "run", cliPath, "compile", ...args]);
	return {
		exitCode: result.exitCode,
		stdout: result.stdout.toString(),
		stderr: result.stderr.toString(),
	};
}

/**
 * File-level $path entries, as generated by routing tools like rogen: every
 * module is mapped individually and the tree does not mirror the filesystem
 * (the server/ folder level is stripped and regrouped). Requires emitted
 * from filesystem-relative positions would break in the synced tree, so
 * imports that cross such a mapping must emit absolute paths.
 */
describe("Rojo aliases from file-level $path entries", () => {
	let projectDir: string;
	let srcDir: string;
	let outDir: string;

	beforeAll(() => {
		projectDir = mkdtempSync(join(tmpdir(), "rbx-tsx-rojo-files-"));
		srcDir = join(projectDir, "src");
		outDir = join(projectDir, "out");
		mkdirSync(join(srcDir, "balloon", "server"), { recursive: true });
		mkdirSync(join(srcDir, "balloon", "shared"), { recursive: true });

		writeFileSync(
			join(projectDir, "wally.toml"),
			'[package]\nname = "tests/file-level-paths"\nversion = "0.0.0"\nregistry = "https://github.com/UpliftGames/wally-index"\nrealm = "shared"\n\n[dependencies]\nAcme = "acme/acme@1.0.0"\n\n[server-dependencies]\nSecretVault = "acme/secret-vault@1.0.0"\n'
		);
		writeFileSync(
			join(projectDir, "default.project.json"),
			JSON.stringify({
				name: "file-level-paths",
				tree: {
					$className: "DataModel",
					ReplicatedStorage: {
						shared: {
							$className: "Folder",
							packages: { $path: "Packages" },
							balloon: {
								$className: "Folder",
								config: { $path: "out/balloon/shared/config.luau" },
							},
						},
					},
					ServerScriptService: {
						server: {
							$className: "Folder",
							packages: { $path: "ServerPackages" },
							balloon: {
								$className: "Folder",
								spawner: { $path: "out/balloon/server/spawner.luau" },
							},
							main: { $path: "out/main.server.luau" },
						},
					},
				},
			})
		);

		writeFileSync(
			join(srcDir, "balloon", "shared", "config.ts"),
			"export const maxBalloons: number = 12\n"
		);
		writeFileSync(
			join(srcDir, "balloon", "server", "spawner.ts"),
			'import { maxBalloons } from "../shared/config";\nimport Acme from "acme";\nimport Vault from "secretvault";\nexport const deps = [Acme, Vault];\nexport function count(): number {\n\treturn maxBalloons;\n}\n'
		);
		writeFileSync(
			join(srcDir, "main.server.ts"),
			'import { count } from "./balloon/server/spawner";\ncount();\n'
		);

		const result = runCompile([srcDir, "-o", outDir]);
		expect(result.exitCode).toBe(0);
	});

	afterAll(() => {
		rmSync(projectDir, { recursive: true, force: true });
	});

	test("cross-boundary import resolves to the aliased tree position", () => {
		const spawner = readFileSync(join(outDir, "balloon", "server", "spawner.luau"), "utf-8");
		expect(spawner).toContain(
			'require(game:GetService("ReplicatedStorage").shared.balloon.config)'
		);
	});

	test("package mounts are auto-detected from the Rojo project per realm", () => {
		const spawner = readFileSync(join(outDir, "balloon", "server", "spawner.luau"), "utf-8");
		expect(spawner).toContain(
			'require(game:GetService("ReplicatedStorage").shared.packages.Acme)'
		);
		expect(spawner).toContain(
			'require(game:GetService("ServerScriptService").server.packages.SecretVault)'
		);
	});

	test("same-service imports emit tree-relative requires", () => {
		// main sits at ServerScriptService.server next to the balloon folder,
		// even though on disk spawner lives under balloon/server/. The relative
		// chain is derived from the two tree positions, not the filesystem.
		const main = readFileSync(join(outDir, "main.server.luau"), "utf-8");
		expect(main).toContain("require(script.Parent.balloon.spawner)");
	});
});
