import type {
  LuauStatement,
  LuauExpression,
  LuauTableEntry,
  LuauParam,
} from "../ast/luau-ast.ts";

export interface CodegenOptions {
  indentStr?: string;
  sourceFile?: string;
}

export function generateLuau(
  statements: LuauStatement[],
  options: CodegenOptions = {}
): string {
  const ctx = new CodegenContext(options.indentStr ?? "    ");
  const lines: string[] = [];

  lines.push("-- Auto-generated by rbx-tsx");
  if (options.sourceFile) {
    lines.push(`-- Source: ${options.sourceFile}`);
  }
  lines.push("");

  for (const stmt of statements) {
    emitStatement(stmt, lines, ctx, 0);
  }

  // Ensure trailing newline
  const result = lines.join("\n");
  return result.endsWith("\n") ? result : result + "\n";
}

class CodegenContext {
  constructor(public indentStr: string) {}

  indent(level: number): string {
    return this.indentStr.repeat(level);
  }
}

// ── Statement emission ──

function emitStatement(
  stmt: LuauStatement,
  lines: string[],
  ctx: CodegenContext,
  depth: number
): void {
  const t = ctx.indent(depth);

  switch (stmt.type) {
    case "local": {
      let line = `${t}local ${stmt.name}`;
      if (stmt.typeAnnotation) {
        line += `: ${stmt.typeAnnotation}`;
      }
      if (stmt.value) {
        line += ` = ${emitExpr(stmt.value, ctx, depth)}`;
      }
      lines.push(line);
      break;
    }

    case "multi-local": {
      const names = stmt.names.join(", ");
      const values = stmt.values.map((v) => emitExpr(v, ctx, depth)).join(", ");
      lines.push(`${t}local ${names} = ${values}`);
      break;
    }

    case "assignment": {
      const target = emitExpr(stmt.target, ctx, depth);
      const value = emitExpr(stmt.value, ctx, depth);
      lines.push(`${t}${target} = ${value}`);
      break;
    }

    case "compound-assignment": {
      const target = emitExpr(stmt.target, ctx, depth);
      const value = emitExpr(stmt.value, ctx, depth);
      lines.push(`${t}${target} ${stmt.op} ${value}`);
      break;
    }

    case "return": {
      if (stmt.value) {
        lines.push(`${t}return ${emitExpr(stmt.value, ctx, depth)}`);
      } else {
        lines.push(`${t}return`);
      }
      break;
    }

    case "function-decl": {
      // Source map comment
      if (stmt.sourceLine && stmt.sourceFile) {
        lines.push(`${t}-- source: ${stmt.sourceFile}:${stmt.sourceLine}`);
      }
      const prefix = stmt.local ? "local function" : "function";
      const params = emitParams(stmt.params);
      let sig = `${t}${prefix} ${stmt.name}(${params})`;
      if (stmt.returnType) {
        sig += `: ${stmt.returnType}`;
      }
      lines.push(sig);
      emitBody(stmt.body, lines, ctx, depth + 1);
      lines.push(`${t}end`);
      break;
    }

    case "if": {
      lines.push(`${t}if ${emitExpr(stmt.condition, ctx, depth)} then`);
      emitBody(stmt.body, lines, ctx, depth + 1);
      if (stmt.elseIfs) {
        for (const ei of stmt.elseIfs) {
          lines.push(`${t}elseif ${emitExpr(ei.condition, ctx, depth)} then`);
          emitBody(ei.body, lines, ctx, depth + 1);
        }
      }
      if (stmt.elseBody) {
        lines.push(`${t}else`);
        emitBody(stmt.elseBody, lines, ctx, depth + 1);
      }
      lines.push(`${t}end`);
      break;
    }

    case "for-numeric": {
      let header = `${t}for ${stmt.var} = ${emitExpr(
        stmt.start,
        ctx,
        depth
      )}, ${emitExpr(stmt.end, ctx, depth)}`;
      if (stmt.step) {
        header += `, ${emitExpr(stmt.step, ctx, depth)}`;
      }
      header += " do";
      lines.push(header);
      emitBody(stmt.body, lines, ctx, depth + 1);
      lines.push(`${t}end`);
      break;
    }

    case "for-in": {
      const vars = stmt.vars.join(", ");
      const iters = stmt.iterators
        .map((i) => emitExpr(i, ctx, depth))
        .join(", ");
      lines.push(`${t}for ${vars} in ${iters} do`);
      emitBody(stmt.body, lines, ctx, depth + 1);
      lines.push(`${t}end`);
      break;
    }

    case "while": {
      lines.push(`${t}while ${emitExpr(stmt.condition, ctx, depth)} do`);
      emitBody(stmt.body, lines, ctx, depth + 1);
      lines.push(`${t}end`);
      break;
    }

    case "repeat-until": {
      lines.push(`${t}repeat`);
      emitBody(stmt.body, lines, ctx, depth + 1);
      lines.push(`${t}until ${emitExpr(stmt.condition, ctx, depth)}`);
      break;
    }

    case "expression-statement": {
      lines.push(`${t}${emitExpr(stmt.expr, ctx, depth)}`);
      break;
    }

    case "do-block": {
      lines.push(`${t}do`);
      emitBody(stmt.body, lines, ctx, depth + 1);
      lines.push(`${t}end`);
      break;
    }

    case "comment": {
      for (const commentLine of stmt.text.split("\n")) {
        lines.push(`${t}-- ${commentLine}`);
      }
      break;
    }

    case "type-alias": {
      lines.push(`${t}type ${stmt.name} = ${stmt.definition}`);
      break;
    }

    case "export-type-alias": {
      lines.push(`${t}export type ${stmt.name} = ${stmt.definition}`);
      break;
    }

    case "break": {
      lines.push(`${t}break`);
      break;
    }

    case "continue": {
      lines.push(`${t}continue`);
      break;
    }
  }
}

function emitBody(
  body: LuauStatement[],
  lines: string[],
  ctx: CodegenContext,
  depth: number
): void {
  for (const stmt of body) {
    emitStatement(stmt, lines, ctx, depth);
  }
}

// ── Expression emission ──

function emitExpr(
  expr: LuauExpression,
  ctx: CodegenContext,
  depth: number
): string {
  switch (expr.type) {
    case "identifier":
      return expr.name;

    case "string":
      return luauStr(expr.value);

    case "number":
      return formatNumber(expr.value);

    case "boolean":
      return String(expr.value);

    case "nil":
      return "nil";

    case "table":
      return emitTable(expr.entries, ctx, depth);

    case "call": {
      const callee = emitExpr(expr.callee, ctx, depth);
      const args = expr.args.map((a) => emitExpr(a, ctx, depth)).join(", ");
      // Wrap function expressions in parens for IIFE: (function() ... end)()
      if (expr.callee.type === "function-expr") {
        return `(${callee})(${args})`;
      }
      return `${callee}(${args})`;
    }

    case "method-call": {
      let obj = emitExpr(expr.object, ctx, depth);
      if (expr.object.type === "if-expr") obj = `(${obj})`;
      const args = expr.args.map((a) => emitExpr(a, ctx, depth)).join(", ");
      return `${obj}:${expr.method}(${args})`;
    }

    case "index": {
      let obj = emitExpr(expr.object, ctx, depth);
      if (expr.object.type === "if-expr") obj = `(${obj})`;
      return `${obj}.${expr.property}`;
    }

    case "bracket-index": {
      let obj = emitExpr(expr.object, ctx, depth);
      if (expr.object.type === "if-expr") obj = `(${obj})`;
      const idx = emitExpr(expr.index, ctx, depth);
      return `${obj}[${idx}]`;
    }

    case "binary": {
      const left = emitExprWrapped(expr.left, expr.op, "left", ctx, depth);
      const right = emitExprWrapped(expr.right, expr.op, "right", ctx, depth);
      return `${left} ${expr.op} ${right}`;
    }

    case "unary": {
      const operand = emitExpr(expr.operand, ctx, depth);
      if (expr.op === "#" || expr.op === "-") {
        return `${expr.op}${operand}`;
      }
      // "not" needs a space
      return `${expr.op} ${
        needsParens(expr.operand, expr.op) ? `(${operand})` : operand
      }`;
    }

    case "if-expr": {
      const cond = emitExpr(expr.condition, ctx, depth);
      const then_ = emitExpr(expr.thenExpr, ctx, depth);
      const else_ = emitExpr(expr.elseExpr, ctx, depth);
      return `if ${cond} then ${then_} else ${else_}`;
    }

    case "function-expr": {
      const params = emitParams(expr.params);
      let header = `function(${params})`;
      if (expr.returnType) {
        header += `: ${expr.returnType}`;
      }

      // Single-return-statement functions can be inlined
      if (
        expr.body.length === 1 &&
        expr.body[0]!.type === "return" &&
        expr.body[0]!.value
      ) {
        const retVal = emitExpr(expr.body[0]!.value, ctx, depth);
        if (retVal.length < 60) {
          return `${header} return ${retVal} end`;
        }
      }

      const bodyLines: string[] = [];
      emitBody(expr.body, bodyLines, ctx, depth + 1);
      const t = ctx.indent(depth);
      return `${header}\n${bodyLines.join("\n")}\n${t}end`;
    }

    case "concat": {
      return expr.parts
        .map((p) => {
          const s = emitExpr(p, ctx, depth);
          // Wrap complex exprs in parens for concat
          if (
            p.type === "binary" ||
            p.type === "if-expr" ||
            p.type === "unary"
          ) {
            return `(${s})`;
          }
          return s;
        })
        .join(" .. ");
    }

    case "template-literal": {
      const escape = (s: string) =>
        s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\{/g, "\\{");
      let result = "`" + escape(expr.head);
      for (const span of expr.spans) {
        result += `{${emitExpr(span.expr, ctx, depth)}}`;
        result += escape(span.text);
      }
      result += "`";
      return result;
    }

    case "varargs":
      return "...";

    case "raw":
      return expr.code;

    case "type-assertion": {
      const inner = emitExpr(expr.expr, ctx, depth);
      return `${inner} :: ${expr.annotation}`;
    }
  }
}

function emitTable(
  entries: LuauTableEntry[],
  ctx: CodegenContext,
  depth: number
): string {
  if (entries.length === 0) return "{}";

  // Check if all entries are short enough for inline
  const inlineParts: string[] = [];
  let totalLen = 2; // for { }
  let canInline = entries.length <= 4;

  for (const entry of entries) {
    const part = emitTableEntry(entry, ctx, depth);
    inlineParts.push(part);
    totalLen += part.length + 2;
    if (totalLen > 80) {
      canInline = false;
      break;
    }
  }

  if (canInline && !inlineParts.some((p) => p.includes("\n"))) {
    return `{ ${inlineParts.join(", ")} }`;
  }

  // Multi-line
  const t = ctx.indent(depth + 1);
  const tClose = ctx.indent(depth);
  const lines = entries.map((entry) => {
    return `${t}${emitTableEntry(entry, ctx, depth + 1)},`;
  });
  return `{\n${lines.join("\n")}\n${tClose}}`;
}

function emitTableEntry(
  entry: LuauTableEntry,
  ctx: CodegenContext,
  depth: number
): string {
  const value = emitExpr(entry.value, ctx, depth);
  if (!entry.key) {
    return value;
  }

  const key = entry.key;
  // String key that's a valid identifier → use plain name
  if (key.type === "string" && isValidLuauIdent(key.value)) {
    return `${key.value} = ${value}`;
  }
  // Otherwise bracket index
  return `[${emitExpr(key, ctx, depth)}] = ${value}`;
}

// ── Helpers ──

function emitParams(params: LuauParam[]): string {
  return params
    .map((p) => {
      if (p.name === "...") return `...: ${p.type ?? "any"}`;
      return p.type ? `${p.name}: ${p.type}` : p.name;
    })
    .join(", ");
}

const PRECEDENCE: Record<string, number> = {
  or: 1,
  and: 2,
  "<": 3,
  ">": 3,
  "<=": 3,
  ">=": 3,
  "~=": 3,
  "==": 3,
  "..": 4,
  "+": 5,
  "-": 5,
  "*": 6,
  "/": 6,
  "//": 6,
  "%": 6,
  "^": 8,
};

function emitExprWrapped(
  expr: LuauExpression,
  parentOp: string,
  side: "left" | "right",
  ctx: CodegenContext,
  depth: number
): string {
  const s = emitExpr(expr, ctx, depth);
  if (expr.type === "binary") {
    const parentPrec = PRECEDENCE[parentOp] ?? 0;
    const childPrec = PRECEDENCE[expr.op] ?? 0;
    if (
      childPrec < parentPrec ||
      (childPrec === parentPrec && side === "right")
    ) {
      return `(${s})`;
    }
  }
  // if-expressions must be parenthesized inside binary ops to avoid ambiguity
  if (expr.type === "if-expr") {
    return `(${s})`;
  }
  return s;
}

function needsParens(expr: LuauExpression, parentOp: string): boolean {
  if (parentOp === "not") {
    return (
      expr.type === "binary" || expr.type === "unary" || expr.type === "if-expr"
    );
  }
  return false;
}

function isValidLuauIdent(s: string): boolean {
  return /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(s) && !LUAU_KEYWORDS.has(s);
}

const LUAU_KEYWORDS = new Set([
  "and",
  "break",
  "do",
  "else",
  "elseif",
  "end",
  "false",
  "for",
  "function",
  "if",
  "in",
  "local",
  "nil",
  "not",
  "or",
  "repeat",
  "return",
  "then",
  "true",
  "until",
  "while",
  "continue",
  "type",
  "export",
]);

function luauStr(s: string): string {
  return `"${s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\0/g, "\\0")}"`;
}

function formatNumber(n: number): string {
  if (n === Infinity) return "math.huge";
  if (n === -Infinity) return "-math.huge";
  if (Object.is(n, -0)) return "-0";
  if (Number.isNaN(n)) return "0/0";
  if (Number.isInteger(n)) return String(n);
  const s = n.toPrecision(10);
  return parseFloat(s).toString();
}
