import ts from "typescript";
import {
  readFileSync,
  writeFileSync,
  readdirSync,
  mkdirSync,
  copyFileSync,
  existsSync,
} from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

/**
 * Generates `src/generated/embedded.ts` (the TS `lib.*.d.ts`, the Roblox/React
 * `types/`, and the `examples/` snippets, all inlined as strings) and then
 * bundles the playground to `dist/` for the browser. Run with `bun run
 * playground/build.ts`.
 */

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const LIB_DIR = join(ROOT, "node_modules", "typescript", "lib");
const TYPES_DIR = join(ROOT, "types");
const EXAMPLES_DIR = join(ROOT, "examples");
const GENERATED = join(HERE, "src", "generated");
const DIST = join(HERE, "dist");

/** BFS the triple-slash `<reference lib=... />` graph from the entry lib. */
function collectLibFiles(): Record<string, string> {
  const out: Record<string, string> = {};
  const queue = ["lib.esnext.d.ts"];
  const seen = new Set<string>();
  while (queue.length) {
    const name = queue.shift()!;
    if (seen.has(name)) continue;
    seen.add(name);
    const path = join(LIB_DIR, name);
    if (!existsSync(path)) continue;
    const text = readFileSync(path, "utf8");
    out["/" + name] = text;
    for (const m of text.matchAll(/\/\/\/\s*<reference\s+lib="([^"]+)"\s*\/>/g)) {
      queue.push("lib." + m[1] + ".d.ts");
    }
    for (const m of text.matchAll(/\/\/\/\s*<reference\s+path="([^"]+)"\s*\/>/g)) {
      queue.push(m[1]!);
    }
  }
  // The host's getDefaultLibFileName resolves to this name; alias it to esnext
  // so the file exists even though `lib: ["lib.esnext.d.ts"]` is what's loaded.
  const defaultName = "/" + ts.getDefaultLibFileName({ target: ts.ScriptTarget.ESNext });
  if (!out[defaultName]) out[defaultName] = out["/lib.esnext.d.ts"]!;
  return out;
}

function collectTypeFiles(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const name of readdirSync(TYPES_DIR)) {
    if (!name.endsWith(".d.ts")) continue;
    out["/types/" + name] = readFileSync(join(TYPES_DIR, name), "utf8");
  }
  return out;
}

// Order the dropdown deliberately; anything not listed falls in afterwards.
const EXAMPLE_ORDER = [
  "react-component.tsx",
  "types.ts",
  "roblox-services.ts",
  "optional-chaining.ts",
  "async-await.ts",
  "flow.ts",
  "regex.ts",
  "decorators.ts",
];

function collectExamples(): { label: string; filename: string; source: string }[] {
  const files = readdirSync(EXAMPLES_DIR).filter(
    (n) => n.endsWith(".ts") || n.endsWith(".tsx")
  );
  const ordered = [
    ...EXAMPLE_ORDER.filter((n) => files.includes(n)),
    ...files.filter((n) => !EXAMPLE_ORDER.includes(n)).sort(),
  ];
  return ordered.map((filename) => ({
    label: filename.replace(/\.(tsx?|jsx?)$/, ""),
    filename,
    source: readFileSync(join(EXAMPLES_DIR, filename), "utf8").trimEnd() + "\n",
  }));
}

function generateEmbedded(): void {
  mkdirSync(GENERATED, { recursive: true });
  const libFiles = collectLibFiles();
  const typeFiles = collectTypeFiles();
  const examples = collectExamples();
  const body =
    `// AUTO-GENERATED by playground/build.ts — do not edit.\n` +
    `export const LIB_FILES: Record<string, string> = ${JSON.stringify(libFiles)};\n` +
    `export const TYPE_FILES: Record<string, string> = ${JSON.stringify(typeFiles)};\n` +
    `export interface Example { label: string; filename: string; source: string }\n` +
    `export const EXAMPLES: Example[] = ${JSON.stringify(examples)};\n`;
  writeFileSync(join(GENERATED, "embedded.ts"), body);
  console.log(
    `embedded ${Object.keys(libFiles).length} lib files, ` +
      `${Object.keys(typeFiles).length} type files, ${examples.length} examples`
  );
}

// Substitute `node:path` / `path` with the browser shim (the compiler only uses
// pure-string posix helpers).
const pathShimPlugin: import("bun").BunPlugin = {
  name: "path-shim",
  setup(build) {
    build.onResolve({ filter: /^(node:)?path$/ }, () => ({
      path: join(HERE, "src", "path-shim.ts"),
    }));
  },
};

async function bundle(): Promise<void> {
  mkdirSync(DIST, { recursive: true });
  const result = await Bun.build({
    entrypoints: [join(HERE, "src", "main.ts")],
    outdir: DIST,
    target: "browser",
    minify: true,
    naming: "bundle.js",
    plugins: [pathShimPlugin],
  });
  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error("playground bundle failed");
  }
  copyFileSync(join(HERE, "index.html"), join(DIST, "index.html"));
  console.log(`bundled → ${join(DIST, "bundle.js")}`);
}

generateEmbedded();
await bundle();
